version: '3.8'

services:
  app:
    container_name: aqi-bot
    build: .
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_URL=${DATABASE_URL}"
      - "BOT_TOKEN=${BOT_TOKEN}"
      - "API_TOKEN=${API_TOKEN}"
      - "STATION_ID=${STATION_ID}"
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_NAME}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
