version: '3.8'

services:
  app-dev:
    container_name: aqi-bot-dev
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "DATABASE_URL=${DATABASE_URL}"
      - "BOT_TOKEN=${BOT_TOKEN}"
      - "API_TOKEN=${API_TOKEN}"
      - "STATION_ID=${STATION_ID}"
    depends_on:
      - postgreshost
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  app-test:
    container_name: aqi-bot-test
    build:
      context: .
      target: testing
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "DATABASE_URL=${DATABASE_URL}"
      - "BOT_TOKEN=${BOT_TOKEN}"
      - "API_TOKEN=${API_TOKEN}"
      - "STATION_ID=${STATION_ID}"
    depends_on:
      - postgreshost

  app-prod:
    container_name: aqi-bot-prod
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "DATABASE_URL=${DATABASE_URL}"
      - "BOT_TOKEN=${BOT_TOKEN}"
      - "API_TOKEN=${API_TOKEN}"
      - "STATION_ID=${STATION_ID}"
    depends_on:
      - postgreshost

  postgreshost:
    container_name: postgresdb
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_NAME}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
